# Compile supplemental figures into a single PDF for manuscript submission.
# Each figure occupies one full page: bold/italic Arial 11 pt title at top,
# figure centred below with 1-inch margins, aspect ratio preserved.
#
# Run from the package root:
#   source("development/manuscript/compile-supplemental-figures.R")
#
# Output: development/manuscript/supplemental_content.pdf
#
# Requirements: png
# install.packages("png")  # if not already installed

library(png)
library(grid)

# ── Figure definitions (descriptive = 1, 2-group = 2, 3-group = 3) ───────────

figures <- list(
  list(
    path  = "vignettes/figures/tern_descriptive.png",
    title = "Supplemental Table 1. A descriptive summary table generated by TernTables."
  ),
  list(
    path  = "vignettes/figures/tern_2_group.png",
    title = "Supplemental Table 2. A two-group comparison table generated by TernTables."
  ),
  list(
    path  = "vignettes/figures/tern_3_group.png",
    title = "Supplemental Table 3. A three-group comparison table generated by TernTables."
  )
)

# ── Layout constants (US Letter: 8.5 x 11 in) ────────────────────────────────

page_w_in   <- 8.5
page_h_in   <- 11.0
margin_in   <- 1.0          # 1-inch margins all sides

# Usable area in inches
usable_w_in <- page_w_in - 2 * margin_in   # 6.5
usable_h_in <- page_h_in - 2 * margin_in   # 9.0

# Title block height in inches (~1 line at 11 pt + padding)
title_h_in  <- 0.45

# Image area height in inches (below title, small gap)
gap_in      <- 0.15
img_area_h_in <- usable_h_in - title_h_in - gap_in

# Convert to NPC (normalised parent coordinates, 0–1)
margin_x_npc   <- margin_in / page_w_in
margin_y_npc   <- margin_in / page_h_in
usable_w_npc   <- usable_w_in / page_w_in
usable_h_npc   <- usable_h_in / page_h_in
title_h_npc    <- title_h_in  / page_h_in
gap_npc        <- gap_in      / page_h_in
img_area_h_npc <- img_area_h_in / page_h_in

# ── Output ────────────────────────────────────────────────────────────────────

out_path <- "development/manuscript/supplemental_content.pdf"
dir.create(dirname(out_path), recursive = TRUE, showWarnings = FALSE)

cairo_pdf(out_path, width = page_w_in, height = page_h_in)

for (fig in figures) {

  img        <- png::readPNG(fig$path)
  dims       <- dim(img)                  # [height_px, width_px, channels]
  img_aspect <- dims[2] / dims[1]        # width / height

  # Compute display size preserving aspect ratio within the available image area
  # Try filling the full usable width first; if that makes it too tall, constrain height.
  trial_w_in <- usable_w_in
  trial_h_in <- trial_w_in / img_aspect
  if (trial_h_in > img_area_h_in) {
    trial_h_in <- img_area_h_in
    trial_w_in <- trial_h_in * img_aspect
  }

  img_w_npc <- trial_w_in / page_w_in
  img_h_npc <- trial_h_in / page_h_in

  # Y positions (NPC, measured from bottom of page)
  title_bottom_npc <- 1 - margin_y_npc - title_h_npc
  img_top_npc      <- title_bottom_npc - gap_npc
  img_centre_y_npc <- img_top_npc - img_h_npc / 2

  grid.newpage()

  # ── Title (bold, italic, Arial 11 pt) at top of usable area ────────────────
  pushViewport(viewport(
    x      = margin_x_npc,
    y      = title_bottom_npc,
    width  = usable_w_npc,
    height = title_h_npc,
    just   = c("left", "bottom")
  ))
  grid.text(
    fig$title,
    x    = 0,
    y    = 1,
    just = c("left", "top"),
    gp   = gpar(fontfamily = "Arial", fontface = "bold.italic",
                fontsize = 11, lineheight = 1.3)
  )
  popViewport()

  # ── Figure centred horizontally in usable area ──────────────────────────────
  pushViewport(viewport(
    x      = 0.5,
    y      = img_centre_y_npc,
    width  = img_w_npc,
    height = img_h_npc,
    just   = "centre"
  ))
  grid.raster(img, width = unit(1, "npc"), height = unit(1, "npc"),
              interpolate = TRUE)
  popViewport()
}

dev.off()

message("Written: ", normalizePath(out_path))
